"""empty message

Revision ID: 0ae0d26e3b71
Revises: a718b7d01906
Create Date: 2022-05-28 00:38:17.924827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae0d26e3b71'
down_revision = 'a718b7d01906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basictest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predata_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('_count', sa.Integer(), nullable=False),
    sa.Column('_set', sa.Integer(), nullable=False),
    sa.Column('user_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['predata_id'], ['predata.id'], name=op.f('fk_basictest_predata_id_predata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_basictest_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_basictest'))
    )
    op.drop_table('basic_test')
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basictest_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_result_basictest_id_basictest'), 'basictest', ['basictest_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_result_basictest_id_basictest'), type_='foreignkey')
        batch_op.drop_column('basictest_id')

    op.create_table('basic_test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('predata_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('_count', sa.INTEGER(), nullable=False),
    sa.Column('_set', sa.INTEGER(), nullable=False),
    sa.Column('user_level', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['predata_id'], ['predata.id'], name='fk_basic_test_predata_id_predata', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_basic_test_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_basic_test')
    )
    op.drop_table('basictest')
    # ### end Alembic commands ###
